name: valorant_lineups
description: "Бесплатные интерактивные лайнапы для Valorant — видео-гайды, карты, агенты, XP."
publish_to: "none"

version: 1.0.34+736775

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.9.0
  cloud_firestore: ^6.4.1
  firebase_auth: ^6.5.1
  google_sign_in: ^6.2.1

  # Networking
  http: ^1.6.0
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1

  # Audio
  audioplayers: ^6.1.0

  # Storage
  shared_preferences: ^2.5.5

  # Ads
  yandex_mobileads: ^7.18.0

  # Video
  video_player: ^2.9.2
  video_compress: ^3.1.2

  # Images
  image_picker: ^1.1.2
  gal: ^1.2.0

  # Paths
  path_provider: ^2.1.4

  # Crypto
  crypto: ^3.0.3

  # Push notifications
  onesignal_flutter: ^5.2.6
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.0

  flutter_native_splash: ^2.4.4

  # YouTube
  youtube_player_flutter: ^9.0.2
  youtube_explode_dart: ^2.3.0

  # Package info
  package_info_plus: ^8.3.0

  # URL launcher
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  image: ^4.2.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/maps/
    - assets/logo/
    - assets/agents/
    - assets/sounds/

# --- App icon --------------------------------------------
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon_dark_gradient.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0D0D0D"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"

# --- Splash screen ------------------------------------------------
flutter_native_splash:
  color: "#0D0D0D"
  image: assets/icon/app_icon_dark_gradient.png
  android: true
  ios: true
  android_12:
    color: "#0D0D0D"
    image: assets/icon/app_icon_dark_gradient.png
    icon_background_color: "#0D0D0D"
